### ISSUE TITLE
Last one for the night.

### ISSUE THREAD

**Issue by Peliia** [Vanemiera/liber-coffee#4]
Name: When Engineer Is The Turret

Author: Pelia

Description: Now here boons, what the burps, the seal will hurt, say and rat my fur, and hurt the meme... Get sparks, send a gamawah! Snurf snurf. It's all about the pose, God.

ID: bcwrd

Loadout:
Perk: Presicion Call-in
Weapon: Punisher
Stratagems: Repair Gun, AT-47, Bastion, Resupply

**Comment by Vanemiera** [comment]
Thanks for the loadouts. All been added to the list.

-Cheers!
